-- 1. Table pour les catégories de produits
CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    slug text NOT NULL UNIQUE,
    description text NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 2. Table pour les produits
CREATE TABLE public.products (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    description text NULL,
    price numeric NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    category_id bigint REFERENCES public.categories(id) ON DELETE RESTRICT,
    owner_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Index pour accélérer la recherche par catégorie
CREATE INDEX products_category_id_idx ON public.products (category_id);

-- 3. Définir les RLS (Row-Level Security) pour les produits
-- Les utilisateurs peuvent lire tous les produits
CREATE POLICY "Utilisateurs peuvent lire tous les produits" ON public.products
  FOR SELECT USING (TRUE);

-- Les propriétaires peuvent insérer, mettre à jour, et supprimer leurs propres produits
CREATE POLICY "Les propriétaires peuvent insérer leurs produits" ON public.products
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Les propriétaires peuvent mettre à jour leurs produits" ON public.products
  FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY "Les propriétaires peuvent supprimer leurs produits" ON public.products
  FOR DELETE USING (auth.uid() = owner_id);

-- 4. Table pour la liste de souhaits (Wishlist)
CREATE TABLE public.wishlist (
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    product_id uuid REFERENCES public.products(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, product_id)
);
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- Les utilisateurs peuvent gérer leur propre liste de souhaits
CREATE POLICY "Utilisateur peut gérer sa propre liste de souhaits" ON public.wishlist
  FOR ALL USING (auth.uid() = user_id);

-- 5. Table pour les commandes (Orders)
CREATE TABLE public.orders (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'pending',
    total_amount numeric NOT NULL,
    shipping_address jsonb NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Les utilisateurs ne peuvent voir que leurs propres commandes
CREATE POLICY "Utilisateurs peuvent voir leurs commandes" ON public.orders
  FOR SELECT USING (auth.uid() = user_id);

-- Les utilisateurs peuvent créer leurs propres commandes
CREATE POLICY "Utilisateurs peuvent créer des commandes" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Dernière modification forcée pour push
-- Dernière modification forcée pour push