-- Création du schéma pour les tables publiques
CREATE TABLE public.profiles (
    id uuid NOT NULL DEFAULT auth.uid(),
    username text NOT NULL,
    full_name text NULL,
    avatar_url text NULL,
    billing_address jsonb NULL,
    payment_method jsonb NULL,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT username_unique UNIQUE (username),
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Créez une fonction pour insérer automatiquement un profil lors d'une nouvelle inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, avatar_url)
  VALUES (NEW.id, split_part(NEW.email, '@', 1), NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Déclencheur (Trigger) qui appelle la fonction après chaque nouvelle insertion dans auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

  -- Table pour les catégories de produits (ex: Électronique, Vêtements, etc.)
CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    slug text NOT NULL UNIQUE,
    description text NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;