-- ================================================================
-- BZMARKET - MIGRATION 1/4 : CRÉATION TABLE SUBCATEGORIES
-- Ajout du système d'attributs dynamiques
-- ================================================================

-- 1. Créer la table subcategories
CREATE TABLE IF NOT EXISTS public.subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL,
    category_id bigint NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    description text NULL,
    
    -- Colonne JSONB pour les templates d'attributs dynamiques
    attributes_config jsonb NULL,
    
    -- Metadata
    icon text NULL,
    is_active boolean DEFAULT true,
    display_order integer DEFAULT 0,
    
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    
    UNIQUE(category_id, slug)
);

-- 2. Ajouter subcategory_id dans products
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS subcategory_id bigint REFERENCES public.subcategories(id) ON DELETE RESTRICT;

-- 3. Créer les index pour performance
CREATE INDEX IF NOT EXISTS idx_subcategories_category_id ON public.subcategories(category_id);
CREATE INDEX IF NOT EXISTS idx_subcategories_slug ON public.subcategories(slug);
CREATE INDEX IF NOT EXISTS idx_subcategories_active ON public.subcategories(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_products_subcategory_id ON public.products(subcategory_id);

-- 4. Trigger pour updated_at
CREATE OR REPLACE FUNCTION update_subcategories_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_subcategories_updated_at ON public.subcategories;
CREATE TRIGGER trigger_update_subcategories_updated_at
    BEFORE UPDATE ON public.subcategories
    FOR EACH ROW
    EXECUTE FUNCTION update_subcategories_updated_at();

-- 5. Row Level Security
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- Tout le monde peut lire les sous-catégories actives
CREATE POLICY "Lecture publique des sous-catégories actives"
    ON public.subcategories
    FOR SELECT
    USING (is_active = true);

-- Seuls les admins peuvent modifier
CREATE POLICY "Admins peuvent gérer les sous-catégories"
    ON public.subcategories
    FOR ALL
    USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- ================================================================
-- FIN MIGRATION 1/4
-- ================================================================
